### ISSUE TITLE
Wrong Filenames in Classify.py

### ISSUE THREAD

**Issue by DennisFaucher** [loicmarie/sign-language-alphabet-recognizer#16]
train.py creates trained_graph.pb and trained_labels.txt. calssify.py tries to open output_graph.pb and output_labels.txt.

**Comment by someshium** [comment]
can you elaborate please?

**Comment by DennisFaucher** [comment]
I cannot even remember. I found another method here: https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect.md
